security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
                login_path: login
                check_path: login
                provider: my_provider

            logout:
                path: /logout
                target: /
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/menu, roles: ROLE_USER }